// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxbX_TCMLvHsjY3ipsXnr9pc9R6zZZ-s',
    appId: '1:684685457024:web:eb5ef62e211ba90c24d865',
    messagingSenderId: '684685457024',
    projectId: 'boxitup',
    authDomain: 'boxitup.firebaseapp.com',
    storageBucket: 'boxitup.appspot.com',
    measurementId: 'G-59E4M4HE0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5NLnRnZMTTUfwR58jEMFx_HJ66pGV6U',
    appId: '1:684685457024:android:fb0cd64176cd6ac524d865',
    messagingSenderId: '684685457024',
    projectId: 'boxitup',
    storageBucket: 'boxitup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcy-F-u9j-umIvVlW01jTM5_E6leZCyjg',
    appId: '1:684685457024:ios:bfc08d2622108d1324d865',
    messagingSenderId: '684685457024',
    projectId: 'boxitup',
    storageBucket: 'boxitup.appspot.com',
    iosClientId: '684685457024-ktff8nd4fg8mo4luj727rjokqq8smn7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxitup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcy-F-u9j-umIvVlW01jTM5_E6leZCyjg',
    appId: '1:684685457024:ios:99691a122174e3c324d865',
    messagingSenderId: '684685457024',
    projectId: 'boxitup',
    storageBucket: 'boxitup.appspot.com',
    iosClientId: '684685457024-vguhj2b00gso0tp1bghhgc5vaa8q742p.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxitup.RunnerTests',
  );
}
