// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtidP2T0ad5erWzgRYZzeBJexOt5ZsHEM',
    appId: '1:701834425864:web:93844e7031ef6f91fc03bd',
    messagingSenderId: '701834425864',
    projectId: 'admin-dashboard-8305c',
    authDomain: 'admin-dashboard-8305c.firebaseapp.com',
    storageBucket: 'admin-dashboard-8305c.appspot.com',
    measurementId: 'G-KQ69W8Z1PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Uwp46-KXliHU94UBY3WcwIB-hnF_neY',
    appId: '1:701834425864:android:0351980451e02d28fc03bd',
    messagingSenderId: '701834425864',
    projectId: 'admin-dashboard-8305c',
    storageBucket: 'admin-dashboard-8305c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHGktH4WLv3WE_v37gvqTXcDyipFhLNYI',
    appId: '1:701834425864:ios:3a431a910c5b625dfc03bd',
    messagingSenderId: '701834425864',
    projectId: 'admin-dashboard-8305c',
    storageBucket: 'admin-dashboard-8305c.appspot.com',
    iosClientId: '701834425864-qgspk6u116pbvkkv3ha5dshe1a30t2sh.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxitup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHGktH4WLv3WE_v37gvqTXcDyipFhLNYI',
    appId: '1:701834425864:ios:5bf0623cedba2996fc03bd',
    messagingSenderId: '701834425864',
    projectId: 'admin-dashboard-8305c',
    storageBucket: 'admin-dashboard-8305c.appspot.com',
    iosClientId: '701834425864-7p4ptv22c189h4b7t7olsi58i9ubgj2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.boxitup.RunnerTests',
  );
}
